USE testdb;

CREATE TABLE IF NOT EXISTS entity(
    added_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(32) NOT NULL,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    body VARCHAR(1024),
    UNIQUE KEY (id)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS user_info(
    uid varchar(32) NOT NULL PRIMARY KEY,
    session_id varchar(32) NOT NULL,
    ip char(17) NOT NULL,
    INDEX(session_id)
) ENGINE=InnoDB;
