
ERR_SERVER_INVALID_CONFIG     = "ERR_SERVER_INVALID_CONFIG"
ERR_SERVER_INVALID_RESULT     = "ERR_SERVER_INVALID_RESULT"
ERR_SERVER_INVALID_PARAMETERS = "ERR_SERVER_INVALID_PARAMETERS"
ERR_SERVER_INVALID_ACTION     = "ERR_SERVER_INVALID_ACTION"
ERR_SERVER_OPERATION_FAILED   = "ERR_SERVER_OPERATION_FAILED"
ERR_SERVER_UNKNOWN_ERROR      = "ERR_SERVER_UNKNOWN_ERROR"
